name: Deploy Bostro Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ secrets.SSH_KEY }}" > ssh-key;
          chmod 0400 ssh-key;

      - run: scp -i ssh-key -r -o StrictHostKeyChecking=no ./ root@103.108.140.108:/root/bostro
      - run: ssh -i ssh-key -o StrictHostKeyChecking=no root@103.108.140.108 "cd /root/bostro && docker compose pull && docker compose up --build --remove-orphans -d"
